POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "uname":"MaFe14",
    "pswd":"12345678"
}
###
POST http://localhost:8080/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWNvbWVuZGF0aW9ucyI6W10sInByb2plY3RzT3duZWQiOltdLCJwcm9qZWN0c1BhcnRpY2lwYW50cyI6W10sIl9pZCI6IjYwYWE4MTlkYjM4NDNmMjkzNGRhY2YwOCIsInVuYW1lIjoiTWFGZTE0IiwiZnVsbG5hbWUiOiJtYXJjIGZlcnJlIiwiZW1haWwiOiJtYXJjQGdtYWlsLmNvbSIsImlhdCI6MTYyMTc4NzAzN30.3-Z4AO2eg5cGKNvlDVclV78bPsL9QOY6djmN4kSCO1I
###
GET http://localhost:8080/api/projects/
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWNvbWVuZGF0aW9ucyI6W10sInByb2plY3RzT3duZWQiOltdLCJwcm9qZWN0c1BhcnRpY2lwYW50cyI6W10sIl9pZCI6IjYwYWE4MTlkYjM4NDNmMjkzNGRhY2YwOCIsInVuYW1lIjoiTWFGZTE0IiwiZnVsbG5hbWUiOiJtYXJjIGZlcnJlIiwiZW1haWwiOiJtYXJjQGdtYWlsLmNvbSIsImlhdCI6MTYyMTc4NzAzN30.3-Z4AO2eg5cGKNvlDVclV78bPsL9QOY6djmN4kSCO1I
###
POST http://localhost:8080/api/users/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWNvbWVuZGF0aW9ucyI6W10sInByb2plY3RzT3duZWQiOltdLCJwcm9qZWN0c1BhcnRpY2lwYW50cyI6W10sIl9pZCI6IjYwYWE4MTlkYjM4NDNmMjkzNGRhY2YwOCIsInVuYW1lIjoiTWFGZTE0IiwiZnVsbG5hbWUiOiJtYXJjIGZlcnJlIiwiZW1haWwiOiJtYXJjQGdtYWlsLmNvbSIsImlhdCI6MTYyMTc4NzAzN30.3-Z4AO2eg5cGKNvlDVclV78bPsL9QOY6djmN4kSCO1I


{
    "uname":"MaFe14"
}